# Generated by Django 5.1.2 on 2024-10-12 01:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=35)),
                ('lastName', models.CharField(max_length=35)),
                ('userName', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('language', models.CharField(max_length=45)),
                ('dateOfBirth', models.DateField()),
                ('signUpDate', models.DateField(auto_now_add=True)),
                ('isVerified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('friendshipID', models.IntegerField(primary_key=True, serialize=False)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_friendships', to='main.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_friendships', to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('chatroomID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_chatrooms', to='main.user')),
                ('participantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_chatrooms', to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chatID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chatType', models.CharField(max_length=5)),
                ('createdAT', models.DateTimeField(auto_now_add=True)),
                ('originalVoiceMsg', models.BinaryField(null=True)),
                ('originalTextMsg', models.TextField()),
                ('translatedTextMsg', models.TextField()),
                ('translatedVoiceMsg', models.BinaryField(null=True)),
                ('chatroomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_chats', to='main.chatroom')),
                ('creatorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chats', to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('verificationID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verificationCode', models.UUIDField()),
                ('verificationType', models.CharField(max_length=20)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_verifications', to='main.user')),
            ],
        ),
    ]
