# Generated by Django 5.1.2 on 2024-10-21 02:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_friendship_friendship_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='friendship_id',
            field=models.UUIDField(db_column='friendship_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
